// Actions are open-ended dotted strings written by the API ("agent.created"). Known ones read as a sentence;
// unknown ones fall back to the verb part in sentence case (see getActivityActionLabel).
export const ActivityActionFormOptions: { id: string; label: string }[] = [
  { id: "agent.created", label: "Created agent" },
  { id: "agent.updated", label: "Agent updated" },
  { id: "agent.duplicated", label: "Duplicated agent" },
  { id: "agent.activated", label: "Activated agent" },
  { id: "agent.deactivated", label: "Deactivated agent" },
  { id: "agent.deleted", label: "Deleted agent" },
  { id: "alert.dismissed", label: "Dismissed an alert" },
  { id: "alert.resolved", label: "Resolved an alert" },
  { id: "alert.dismissed_all", label: "Dismissed alerts" },
  { id: "automation.rule_triggered", label: "Automation rule ran" },
  { id: "automation_rule.created", label: "Created automation rule" },
  { id: "automation_rule.updated", label: "Updated automation rule" },
  { id: "automation_rule.enabled", label: "Enabled automation rule" },
  { id: "automation_rule.disabled", label: "Disabled automation rule" },
  { id: "automation_rule.deleted", label: "Deleted automation rule" },
  { id: "call.received", label: "Inbound call received" },
  { id: "call.started", label: "Call started" },
  { id: "call.ended", label: "Call completed" },
  { id: "call.transferred", label: "Call transferred to a person" },
  { id: "call.failed", label: "Call failed" },
  { id: "call.stopped", label: "Stopped a call" },
  { id: "call.action_retried", label: "Retried a CRM update" },
  { id: "call.recording_downloaded", label: "Downloaded a call recording" },
  { id: "company.created", label: "Created company" },
  { id: "company.updated", label: "Updated company details" },
  { id: "company.calling_hours_updated", label: "Updated calling hours" },
  { id: "company.deletion_requested", label: "Requested company deletion" },
  { id: "company.deletion_cancelled", label: "Cancelled company deletion" },
  { id: "contact.created", label: "Created contact" },
  { id: "contact.updated", label: "Updated contact" },
  { id: "contact.deleted", label: "Deleted contact" },
  { id: "contact.imported", label: "Imported contacts" },
  { id: "contact.synced_from_crm", label: "Synced contact from CRM" },
  { id: "contact.do_not_call_changed", label: "Changed “Do not call” setting" },
  { id: "crm.action_requested", label: "CRM update requested" },
  { id: "crm.action_rejected", label: "CRM update rejected" },
  { id: "crm.action_executed", label: "CRM updated" },
  { id: "crm.action_failed", label: "CRM update failed" },
  { id: "crm.action_needs_attention", label: "CRM update needs attention" },
  { id: "crm_field_mappings.updated", label: "Updated field matching" },
  { id: "crm_tool.created", label: "Added CRM action" },
  { id: "crm_tool.updated", label: "Updated CRM action" },
  { id: "crm_tool.deleted", label: "Removed CRM action" },
  { id: "integration.connected", label: "Connected integration" },
  { id: "integration.updated", label: "Updated integration" },
  { id: "integration.tested", label: "Tested integration connection" },
  { id: "integration.deleted", label: "Disconnected integration" },
  { id: "knowledge.created", label: "Created knowledge source" },
  { id: "knowledge.uploaded", label: "Knowledge source uploaded" },
  { id: "knowledge.connected", label: "Connected knowledge source" },
  { id: "knowledge.refreshed", label: "Refreshed knowledge source" },
  { id: "knowledge.version_created", label: "Saved a new knowledge version" },
  { id: "knowledge.version_restored", label: "Restored a knowledge version" },
  { id: "knowledge.deleted", label: "Deleted knowledge source" },
  { id: "phone_number.imported", label: "Imported phone number" },
  { id: "phone_number.provisioned", label: "Bought phone number" },
  { id: "phone_number.updated", label: "Updated phone number" },
  { id: "phone_number.released", label: "Released phone number" },
  { id: "retry_rule.updated", label: "Updated retry rule" },
  { id: "scheduled_call.created", label: "Scheduled a call" },
  { id: "scheduled_call.rescheduled", label: "Rescheduled a call" },
  { id: "scheduled_call.canceled", label: "Canceled a scheduled call" },
  { id: "scheduled_call.retry_scheduled", label: "Retry scheduled" },
  { id: "scheduled_call.transfer_follow_up_created", label: "Follow-up scheduled after a transfer" },
  { id: "scheduled_call.dispatch_failed", label: "Scheduled call could not start" },
  { id: "team.member_invited", label: "Invited team member" },
  { id: "team.invitation_resent", label: "Resent team invitation" },
  { id: "team.invitation_revoked", label: "Revoked team invitation" },
  { id: "team.invitation_accepted", label: "Accepted team invitation" },
  { id: "team.member_updated", label: "Updated team member" },
  { id: "team.member_removed", label: "Removed team member" },
  { id: "team.member_left", label: "Left the company" },
  { id: "team.agent_access_updated", label: "Updated agent access" },
];

/** "call.recording_downloaded" -> "Recording downloaded" when the action is not listed above. */
export function getActivityActionLabel(action: string): string {
  const known = ActivityActionFormOptions.find((option) => option.id === action)?.label;
  if (known) return known;
  const verb = (action.split(".").pop() ?? action).replace(/_/g, " ").trim();
  return verb ? verb.charAt(0).toUpperCase() + verb.slice(1) : action;
}
