// Centralized API endpoints (paths relative to the API base URL).
export const ApiRoutes = {
  auth: {
    register: "/auth/email/register",
    login: "/auth/email/login",
    forgotPassword: "/auth/forgot-password",
    resetPassword: "/auth/reset-password",
    verifyEmail: "/auth/verify-email",
    resendVerification: "/auth/resend-verification",
    me: "/auth/me",
    changePassword: "/auth/change-password",
    logout: "/auth/logout",
  },
  company: {
    list: "/companies",
    current: "/company",
    callingHours: "/company/calling-hours",
    members: "/company/members",
    member: (id: string) => `/company/members/${id}`,
    memberAgentAccess: (id: string) => `/company/members/${id}/agent-access`,
    leave: "/company/leave",
    invitations: "/company/invitations",
    invitation: (id: string) => `/company/invitations/${id}`,
    resendInvitation: (id: string) => `/company/invitations/${id}/resend`,
    deletionStatus: "/company/deletion-status",
    deletionRequest: "/company/deletion-request",
  },
  invitations: {
    preview: "/invitations/preview",
    accept: "/invitations/accept",
  },
  dashboard: "/dashboard",
  analytics: {
    usage: "/analytics/usage",
    timeseries: "/analytics/usage/timeseries",
  },
  alerts: {
    root: "/alerts",
    summary: "/alerts/summary",
    resolve: (id: string) => `/alerts/${id}/resolve`,
    dismiss: (id: string) => `/alerts/${id}/dismiss`,
    dismissAll: "/alerts/dismiss-all",
  },
  activityLog: "/activity-log",
  agents: {
    root: "/agents",
    detail: (id: string) => `/agents/${id}`,
    duplicate: (id: string) => `/agents/${id}/duplicate`,
    overview: (id: string) => `/agents/${id}/overview`,
    readiness: (id: string) => `/agents/${id}/readiness`,
    activate: (id: string) => `/agents/${id}/activate`,
    deactivate: (id: string) => `/agents/${id}/deactivate`,
    resync: (id: string) => `/agents/${id}/resync`,
    goalItems: (id: string) => `/agents/${id}/goal-items`,
    questions: (id: string) => `/agents/${id}/questions`,
    outcomes: (id: string) => `/agents/${id}/outcomes`,
    transferOutcomes: (id: string) => `/agents/${id}/transfer-outcomes`,
    crmTools: (id: string) => `/agents/${id}/crm-tools`,
    knowledgeSources: (id: string) => `/agents/${id}/knowledge-sources`,
    retryRule: (id: string) => `/agents/${id}/retry-rule`,
    access: (id: string) => `/agents/${id}/access`,
  },
  voices: "/voices",
  calls: {
    root: "/calls",
    filterStats: "/calls/stats/filters",
    test: "/calls/test",
    detail: (id: string) => `/calls/${id}`,
    events: (id: string) => `/calls/${id}/events`,
    recording: (id: string) => `/calls/${id}/recording`,
    recordingDownload: (id: string) => `/calls/${id}/recording/download`,
    retryAction: (id: string, actionId: string) => `/calls/${id}/actions/${actionId}/retry`,
    stop: (id: string) => `/calls/${id}/stop`,
  },
  scheduledCalls: {
    root: "/scheduled-calls",
    counts: "/scheduled-calls/counts",
    cancelForContact: "/scheduled-calls/cancel-for-contact",
    detail: (id: string) => `/scheduled-calls/${id}`,
  },
  automationRules: {
    root: "/automation-rules",
    detail: (id: string) => `/automation-rules/${id}`,
    enabled: (id: string) => `/automation-rules/${id}/enabled`,
  },
  contacts: {
    root: "/contacts",
    import: "/contacts/import",
    syncFromCrm: "/contacts/sync-from-crm",
    detail: (id: string) => `/contacts/${id}`,
  },
  knowledge: {
    root: "/knowledge",
    upload: "/knowledge/upload",
    connect: "/knowledge/connect",
    stats: "/knowledge/stats",
    detail: (id: string) => `/knowledge/${id}`,
    agents: (id: string) => `/knowledge/${id}/agents`,
    refresh: (id: string) => `/knowledge/${id}/refresh`,
    versions: (id: string) => `/knowledge/${id}/versions`,
    version: (id: string, version: number | string) => `/knowledge/${id}/versions/${version}`,
    restoreVersion: (id: string, version: number | string) =>
      `/knowledge/${id}/versions/${version}/restore`,
  },
  integrations: {
    root: "/integrations",
    providers: "/integrations/providers",
    internalFields: "/integrations/crm/internal-fields",
    detail: (id: string) => `/integrations/${id}`,
    test: (id: string) => `/integrations/${id}/test`,
    agents: (id: string) => `/integrations/${id}/agents`,
    crmFields: (id: string) => `/integrations/${id}/crm-fields`,
    fieldMappings: (id: string) => `/integrations/${id}/field-mappings`,
    crmTools: (id: string) => `/integrations/${id}/crm-tools`,
    crmTool: (id: string, toolId: string) => `/integrations/${id}/crm-tools/${toolId}`,
    oauthStart: (provider: string) => `/integrations/oauth/${provider}/start`,
  },
  phoneNumbers: {
    root: "/phone-numbers",
    provision: "/phone-numbers/provision",
    import: "/phone-numbers/import",
    detail: (id: string) => `/phone-numbers/${id}`,
    agent: (id: string) => `/phone-numbers/${id}/agent`,
  },
  pricing: "/pricing",
} as const;
