import type { Metadata } from "next";
import { Inter, EB_Garamond, Geist_Mono } from "next/font/google";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Providers } from "./providers";
import "./globals.css";

// Body, navigation, captions, buttons — see DESIGN.MD Typography.
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

// Open-source substitute for the licensed Waldenburg Light display serif —
// DESIGN.MD "Note on Font Substitutes". EB Garamond ships no 300 weight, so 400
// is the lightest face available; display classes still request font-light.
const ebGaramond = EB_Garamond({
  variable: "--font-eb-garamond",
  weight: ["400"],
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${ebGaramond.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          <TooltipProvider>{children}</TooltipProvider>
        </Providers>
      </body>
    </html>
  );
}
